### ISSUE TITLE
Can't restart vagrant machine

### ISSUE THREAD

**Issue by gianluca-sabena** [dcos/dcos-vagrant#73] opened 2016-06-08 09:18 UTC
I can't restart vagrant machines

The problem occurs on master and agent
The problem occurs with box 0.6.0 and 0.6.3
Vagrant version: 1.8.1
Mac os x: 10.10.5
Vbox: 5.0.20 r106931

How to reproduce:

- Start a minimal cluster (1 master, 1 agent, 1 boot)
- run `vagrant halt`
- run `vagrant up`

The vagrant machine halt on boot on message `a1: Configuring and enabling network interfaces...`

If I enable vagrant log info, boot process stops at this point:
```
==> a1: Configuring and enabling network interfaces...
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: configure_networks [#<Vagrant::Machine: a1 (VagrantPlugins::ProviderVirtualBox::Provider)>, [{:type=>:static, :adapter_ip=>"192.168.65.1", :ip=>"192.168.65.111", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1}]] (redhat)
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: flavor [#<Vagrant::Machine: a1 (VagrantPlugins::ProviderVirtualBox::Provider)>] (redhat)
 INFO ssh: Execute: cat /etc/redhat-release (sudo=true)
 INFO ssh: SSH is ready!
 INFO ssh: Execute:  (sudo=false)
 INFO guest: Execute capability: network_scripts_dir [#<Vagrant::Machine: a1 (VagrantPlugins::ProviderVirtualBox::Provider)>] (redhat)
 INFO ssh: Execute: /usr/sbin/biosdevname &>/dev/null; echo $? (sudo=true)
 INFO ssh: Execute: ls /sys/class/net | egrep -v lo\|docker (sudo=true)
 INFO ssh: Execute: cat /sys/class/net/dummy0/address (sudo=true)
 INFO ssh: Execute: cat /sys/class/net/enp0s3/address (sudo=true)
 INFO ssh: Execute: cat /sys/class/net/enp0s8/address (sudo=true)
 INFO ssh: Execute: cat /sys/class/net/spartan/address (sudo=true)
 INFO ssh: Execute: touch /etc/sysconfig/network-scripts/ifcfg-enp0s3 (sudo=true)
 INFO ssh: Execute: sed -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' /etc/sysconfig/network-scripts/ifcfg-enp0s3 > /tmp/vagrant-ifcfg-enp0s3 (sudo=true)
 INFO ssh: Execute: cat /tmp/vagrant-ifcfg-enp0s3 > /etc/sysconfig/network-scripts/ifcfg-enp0s3 (sudo=true)
 INFO ssh: Execute: rm -f /tmp/vagrant-ifcfg-enp0s3 (sudo=true)
 INFO ssh: Execute: cat /tmp/vagrant-network-entry_enp0s3 >> /etc/sysconfig/network-scripts/ifcfg-enp0s3

if command -v nmcli &>/dev/null; then
  if command -v systemctl &>/dev/null && systemctl -q is-enabled NetworkManager &>/dev/null; then
    nmcli c reload enp0s3
  elif command -v service &>/dev/null && service NetworkManager status &>/dev/null; then
    nmcli c reload enp0s3
  fi
fi

/sbin/ifdown enp0s3
/sbin/ifup enp0s3

rm -f /tmp/vagrant-network-entry_enp0s3
 (sudo=true)
```

**Comment by gianluca-sabena** [comment] 2016-06-08 09:21
It is a vagrant problem, see https://github.com/mitchellh/vagrant/issues/7401 Need to wait for vagrant 1.8.3

**Comment by karlkfi** [comment] 2016-06-08 20:38
Duplicate of jira ticket: https://dcosjira.atlassian.net/browse/VAGRANT-7 SO I'm gonna close this one.

We're not using multiple private network IPs on the same machine, so i'm not sure that's the cause.

**Closed by karlkfi** 2016-06-08 20:38 UTC
