### ISSUE TITLE
Ubuntu 16: VM doesn't start, process stuck on network configuration.

### ISSUE THREAD

**Issue by estebanlll** [dcos/dcos-vagrant#65] opened 2016-05-26 08:48 UTC
Since few days I have the issue that every time I do _vagrant up_ the process stuck and doesn't continue. And the only way to make it works is destroying all the VMs and start from scratch.

```bash
$ vagrant up m1 a1 a2 p1 boot
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'a1' up with 'virtualbox' provider...
Bringing machine 'a2' up with 'virtualbox' provider...
Bringing machine 'p1' up with 'virtualbox' provider...
Bringing machine 'boot' up with 'virtualbox' provider...
==> m1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> m1: Clearing any previously set forwarded ports...
==> m1: Clearing any previously set network interfaces...
==> m1: Preparing network interfaces based on configuration...
    m1: Adapter 1: nat
    m1: Adapter 2: hostonly
==> m1: Forwarding ports...
    m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
    m1: SSH address: 127.0.0.1:2222
    m1: SSH username: vagrant
    m1: SSH auth method: private key
    m1: Warning: Remote connection disconnect. Retrying...
    m1: Warning: Remote connection disconnect. Retrying...
    m1: Warning: Remote connection disconnect. Retrying...
==> m1: Machine booted and ready!
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
```

Versions:
> VirtualBox: 5.0.20
> Vagrant box: 0.6.3
> Vagrant: 1.8.1
> DC/OS: 1.7
> DC/O vagrant: v0.7.0
> Ubuntu: 16.04

Is anyone with the same issue?

**Comment by karlkfi** [comment] 2016-05-26 19:22
I haven't had confirmed success on Ubuntu 16, but haven't had it triaged yet either. Ubuntu 14 and 15 should work as the host OS.

**Comment by juanjoserivera** [comment] 2016-05-27 14:26
Same problem here, Have anyone solved this?

**Comment by xyangwang** [comment] 2016-05-30 14:44
I have the same problem.`override.vm.network :private_network, ip: machine_type['ip']` stuck the process.

**Comment by xyangwang** [comment] 2016-05-31 07:34
After first time run the `vagrant up m1 boot a1 p1`, I change the 213 line in Vagrantfile:
`override.vm.network :private_network, ip: machine_type['ip']` to `override.vm.network :private_network, ip: machine_type['ip'], auto_config: false`
It is solved! You can try it.
@estebanlll @karlkfi @juanjoserivera

**Comment by estebanlll** [comment] 2016-05-31 15:25
Nice, thanks @xyangwang, now I can continue from where I left. 
Btw, can it be related to the issue of the virtualbox modules aren't signed for Ubuntu 16.04 and they are not properly integrated on the kernel and later on it generates this behavior on vagrant?

**Comment by juanjoserivera** [comment] 2016-05-31 15:34
Thanks @xyangwang, it worked!, looks like this problem is not only related to ubuntu hosts, I am running this on Windows 7 and I had same issue.

**Comment by karlkfi** [comment] 2016-05-31 20:32
Not sure why that would fix things...

The `Configuring and enabling network interfaces...` message is printed here: 
https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action/network.rb#L130

The CentOS network is configured here:
https://github.com/mitchellh/vagrant/blob/master/plugins/guests/debian/cap/configure_networks.rb#L12

I see an Ubuntu 16.04 comment in there: 
https://github.com/mitchellh/vagrant/blob/master/plugins/guests/debian/cap/configure_networks.rb#L46

Looks like it was added March 20 (very recently):
https://github.com/mitchellh/vagrant/commit/0505771481222b4893daa5454ff6c9c16f471fa4

So it's possible that an upgrade of Vagrant (or building from master) might also fix your problem.

**Comment by karlkfi** [comment] 2016-05-31 20:34
Vagrant v1.8.1 was released on Dec 24, 2015. So it wont contain the fix listed above. You'll need to build Vagrant from master in order to use it on Ubuntu 16.04 with Debian boxes.

**Comment by karlkfi** [comment] 2016-05-31 20:45
on second thought… that’s for ubuntu 16 guests, not hosts... I doubt CentOS would error without that change,

**Comment by karlkfi** [comment] 2016-05-31 20:51
Here's another bug that affects Ubuntu 16 that is only fixed on master: https://github.com/mitchellh/vagrant/issues/7073

I've added a note to build from source: https://github.com/dcos/dcos-vagrant#operating-system

**Comment by karlkfi** [comment] 2016-05-31 21:56
Ok, I've now tested Ubuntu 16 myself and verified that even building from source does not work because plugins cannot be installed.

Fix: https://github.com/mitchellh/vagrant/pull/7376

Unfortunately, it looks like releases are pretty far apart. So I'm marking Ubuntu 16 as not supported until this is resolved.

**Comment by karlkfi** [comment] 2016-05-31 22:06
FWIW, the problem is with Vagrant 1.8.1 being incompatible with Ruby 2.3. 

Ubuntu 16 comes with Ruby 2.3 "manually installed" in a way that can't easily be downgraded or reinstalled via apt-get.

**Comment by karlkfi** [comment] 2016-05-31 22:17
I've clarified that Ubuntu 16 is currently unsupported: https://github.com/dcos/dcos-vagrant#operating-system

Sorry guys, but I don't want to have to manually manage `/etc/hosts` because Vagrant won't let you install a plugin.

**Closed by karlkfi** 2016-05-31 22:17 UTC
