### ISSUE TITLE
Connection refused trying to login using github/google

### ISSUE THREAD

**Issue by quintona** [dcos/dcos-vagrant#58] opened 2016-05-10 22:35 UTC
I have followed the install instructions and I can access m1.dcos. It provides me with the options to login using github, google or Microsoft. I have tried both google and github and in both cases I get an error ```Unable to login to your DC/OS cluster. Clusters must be connected to the internet.```. I have done some debugging:

- I can ssh into any of the boxes, and I can ping the internet from all of them (ping google or wget google works). 
- There is no firewall running on my host machine. 
- I have checked the logs in /var/log on m1, but no obvious errors 
- there is nothing in the journals that I can see
- If I list all the units from systemd I get the following: 

``` 
● cloud-final.service                                                                 not-found inactive   dead            cloud-final.service
  cpupower.service                                                                    loaded    inactive   dead            Configure CPU power related settings
  crond.service                                                                       loaded    active     running         Command Scheduler
  dbus.service                                                                        loaded    active     running         D-Bus System Message Bus
  dcos-adminrouter-reload.service                                                     loaded    inactive   dead            Admin Router Reloader: Reload admin router to get new DNS
  dcos-adminrouter.service                                                            loaded    active     running         Admin Router: A high performance web server and a reverse proxy server
  dcos-cluster-id.service                                                             loaded    inactive   dead            Cluster ID: Generates anonymous DC/OS Cluster ID
  dcos-cosmos.service                                                                 loaded    active     running         Package Service: DC/OS Packaging API
  dcos-ddt.service                                                                    loaded    active     running         Diagnostics: DC/OS Distributed Diagnostics Tool Master API and Aggregation Servic
  dcos-download.service                                                               loaded    inactive   dead            Pkgpanda: Download DC/OS to this host.
  dcos-epmd.service                                                                   loaded    active     running         Erlang Port Mapping Daemon: DC/OS Erlang Port Mapping Daemon
  dcos-exhibitor.service                                                              loaded    active     running         Exhibitor: Zookeeper Supervisor Service
  dcos-gen-resolvconf.service                                                         loaded    inactive   dead            Generate resolv.conf: Update systemd-resolved for MesosDNS
  dcos-history-service.service                                                        loaded    active     running         Mesos History: DC/OS Resource Metrics History Service/API
  dcos-keepalived.service                                                             loaded    inactive   dead            Keepalived: LVS and VRRP High Availability Monitor
  dcos-logrotate.service                                                              loaded    inactive   dead            Logrotate: Rotate various logs on the system
  dcos-marathon.service                                                               loaded    active     running         Marathon: DC/OS Init System
  dcos-mesos-dns.service                                                              loaded    active     running         Mesos DNS: DNS based Service Discovery
  dcos-mesos-master.service                                                           loaded    active     running         Mesos Master: DC/OS Mesos Master Service
  dcos-minuteman.service                                                              loaded    active     running         Layer 4 Load Balancer: DC/OS Layer 4 Load Balancing Service
  dcos-oauth.service                                                                  loaded    active     running         OAuth: OAuth Authentication Service
  dcos-setup.service                                                                  loaded    inactive   dead            Pkgpanda: Specialize DC/OS for this host.
  dcos-signal.service                                                                 loaded    inactive   dead            Signal: DC/OS Telemetry and Tracking Service
  dcos-spartan-watchdog.service                                                       loaded    activating start-pre start DNS Dispatcher Watchdog: Make sure spartan is running
  dcos-spartan.service                                                                loaded    active     running         DNS Dispatcher: An RFC5625 Compliant DNS Forwarder
● display-manager.service                                                             not-found inactive   dead            display-manager.service
  dm-event.service                                                                    loaded    inactive   dead            Device-mapper event daemon
  docker-storage-setup.service                                                        loaded    inactive   dead            Docker Storage Setup
  docker.service                                                                      loaded    active     running         Docker Application Container Engine
  dracut-shutdown.service                                                             loaded    inactive   dead            Restore /run/initramfs
  emergency.service                                                                   loaded    inactive   dead            Emergency Shell
● exim.service                                                                        not-found inactive   dead            exim.service
  getty@tty1.service                                                                  loaded    active     running         Getty on tty1
● ip6tables.service                                                                   not-found inactive   dead            ip6tables.service
● iptables.service                                                                    not-found inactive   dead            iptables.service
  irqbalance.service                                                                  loaded    active     running         irqbalance daemon
● kdump.service                                                                       loaded    failed     failed          Crash recovery kernel arming
```

So, the only failed service I can see if kdump, and the outward connectivity from the internet seems ok. I assume then that there is some kind of inbound connectivity issue for a callback into the vagrant environment, but that wouldn't make much sense in the case of vagrant. Is there some way to just login with local credentials without using the delegated auth?

**Comment by karlkfi** [comment] 2016-05-11 00:37
What environment are you running (vbox, vagrant, OS)?

**Comment by quintona** [comment] 2016-05-11 02:53
Vagrant 1.8.1
Virtual box 5.0.20
OSX 10.11.2

**Comment by quintona** [comment] 2016-05-11 04:28
Update: I can login. The only thing I did was ssh into m1 and then run the dos-auth command. This simply printed out the help and exited. I can now login. Strange.

**Comment by karlkfi** [comment] 2016-05-11 17:36
Is it reproducible?

**Comment by piwi3910** [comment] 2016-05-12 10:09
same issue as above
running same versions of vagrant and VB but on fedora 23

**Comment by piwi3910** [comment] 2016-05-12 10:17
can you supply me the workaround, running the dcos-oauth does print just the help but still no login

**Comment by karlkfi** [comment] 2016-05-12 15:44
Did you change wlans between deploying the cluster and trying to log in? I've seen issues before where DNS automatically changing on the host makes VMs lose connectivity.

**Comment by piwi3910** [comment] 2016-05-12 15:58
No. No changes.

Sent from my iPhone

On May 12, 2016, at 17:44, Karl Isenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you change wlans between deploying the cluster and trying to log in? I've seen issues before where DNS automatically changing on the host makes VMs lose connectivity.

**Comment by jgarcia-mesosphere** [comment] 2016-05-16 17:41
It looks like the resolver service has been inactivated, pls reactivate it and try again:

```  dcos-gen-resolvconf.service                                                         loaded    inactive   dead            Generate resolv.conf: Update systemd-resolved for MesosDNS
```

**Comment by piwi3910** [comment] 2016-05-17 11:50
the service is running fine.
But it did notice that i can ping outside on ip, but not in name.
i see these nameservers on the m1, no idea what they are.
If i replace with 8.8.8.8 i still have issues.
nameserver 198.51.100.1
nameserver 198.51.100.2
nameserver 198.51.100.3

Other Vagrant boxes on the same net have no issues using 8.8.8.8 or my localhost

**Comment by activatedgeek** [comment] 2016-05-17 11:52
@piwi3910 Replacing will not help because the `/etc/resolve.conf` is overwritten by DC/OS services. Can you try rebooting your systems?

**Comment by bendalby82** [comment] 2016-05-17 12:05
@activatedgeek - Do you mean reboot system hosting Vagrant? Will give it a try.

Also having same problem. Tried logging into m1 and restarting dcos-gen-resolvconf.service. I notice it runs and then returns to inactive state:

    [vagrant@m1 /]$ sudo systemctl restart dcos-gen-resolvconf.service
    [vagrant@m1 /]$ systemctl status dcos-gen-resolvconf.service
    ● dcos-gen-resolvconf.service - Generate resolv.conf: Update systemd-resolved for MesosDNS
       Loaded: loaded (/opt/mesosphere/packages/spartan--8d65d30e42d14bece1c3b46d2ea8e3571451cd56/dcos.target.wants/dcos-gen-resolvconf.service;     enabled; vendor preset: disabled)
       Active: inactive (dead) since Tue 2016-05-17 04:16:34 PDT; 14s ago
      Process: 15518 ExecStart=/opt/mesosphere/bin/gen_resolvconf.py /etc/resolv.conf (code=exited, status=0/SUCCESS)
     Main PID: 15518 (code=exited, status=0/SUCCESS)
    
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: # Generated by gen_resolvconf.py. Do not edit.
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: # Change configuration options by changing DC/OS cluster configuration.
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: # This file must be overwritten regularly for proper cluster operation around
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: # master failure.
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: options timeout:1
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: options attempts:3
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: nameserver 198.51.100.1
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: nameserver 198.51.100.2
    May 17 04:16:34 m1.dcos gen_resolvconf.py[15518]: nameserver 198.51.100.3
    May 17 04:16:34 m1.dcos systemd[1]: Started Generate resolv.conf: Update systemd-resolved for MesosDNS.
    [vagrant@m1 /]$`

**Comment by piwi3910** [comment] 2016-05-17 12:10
Laptop has already been rebooted, and used on different internet connections.
Already tried it on different hosts all running different versions of vagrant.
I don't think it's a host issue boys. As why would other vagrant boxes run fine. And multiple different people experience the same issue. 
In version 1.7, anyway to just disable authentication till this gets fixed?

**Comment by piwi3910** [comment] 2016-05-17 13:33
ok i have disabled oauth, and able to login to the dashboard.
I have found it's really a dns issue, as i cannot install packages.
I see in the dcos_generate_config.sh version 1.7 file the 3 nameservers 198.51.100.1 2 and 3
in the config-1.7.yaml i see 8.8.8.8 however.
So not sure where what gets used and why not overwritten.
For me i have tested the 3 different nameservers from different servers, they don't work.

**Comment by activatedgeek** [comment] 2016-05-17 13:37
@piwi3910 Well, I have also been struggling with the same problem since the release. I also made my custom box and still got the same issues.

Hey @karlkfi, it looks like there are people finally with the same problem as mine.

**Comment by bendalby82** [comment] 2016-05-17 14:11
Verified as per @piwi3910 with following steps:
1. Added oauth_enabled: 'false' to /etc/config-1.7.yaml 
2. vagrant destroy -f
3. vagrant up m1 a1 p1 boot

Can access dashboard. 
Cannot install packages.

**Comment by piwi3910** [comment] 2016-05-17 14:31
i have no clue why, but in /opt/mesosphere/bin/gen_resolvconf.py these values are hard coded.
Can anyone tell me why this is hard coded looking at the script.

**Comment by piwi3910** [comment] 2016-05-17 14:38
ok i'm a bit further.
It seems the ip's used are put on your first boxes.
meaning if you ifconfig, you will see these ranges are local.
So a local dns server should run on the vagrant box for this to work. I'll investigate further

**Comment by piwi3910** [comment] 2016-05-17 14:43
so all the 3 ip's are running on your m1 node,
and a process called beam is opening port 53, but no dns resolving on it.
I'm lost now, i have no clue what beam is

**Comment by piwi3910** [comment] 2016-05-17 15:12
ok i have pin point the problem.
the bizarr ip's in resolve.conf point to a service called spartan.
The service is running fine and resolved internal names like zk-1.zk and others
In so i can conclude spartan is running fine.
Also the logs don't show anything else then that's it's running fine.
it seems spartan should forward everything that it cannot resolve to 8.8.8.8, and here it seems it's not working. any Dcos-spartan people know how to debug this thing. m1 has no tools on it, like nslookup or dig, so it's pretty difficult to debug

**Comment by karlkfi** [comment] 2016-05-17 15:44
You can `yum install -y bind-utils` to install dig and nslookup.

**Comment by karlkfi** [comment] 2016-05-17 15:52
> But it did notice that i can ping outside on ip, but not in name.

That did you ping that didn't work?
Can you resolve m1.dcos?
Can you resolve google.com?

**Comment by anthonyskipper** [comment] 2016-05-17 17:11
I had the same problem.  I eventually tracked it down to the internal specified DNS servers were not resolving due to a routing bug.  Even after I fixed the routing problem spartan seemed to be iffy for a while until the entire node was restarted. 

The bigger problem is that it's bad form to override the resolv.conf file in the way that is happening here.  Many enterprises treat this an an immutable file controlled by external configuration systems.

**Comment by karlkfi** [comment] 2016-05-17 17:26
@anthonyskipper how did you resolve the "routing configuration issue"?

**Comment by anthonyskipper** [comment] 2016-05-17 18:04
The routing problem wasn't a dcos issue.  The routing issue was that  virtualbox uses a natted link as primary interface, and the bridged interface wasn't the default route.  The dcos software all worked, but it couldn't resolve externally.  After I realized dns was an issue I fixed the default route to the bridged interface and I could reach the dns server.  However now spartan was the issue.(I think)   I restarted all the vms and everything worked.

**Comment by karlkfi** [comment] 2016-05-17 18:59
@anthonyskipper: dcos-vagrant should be automatically setting up your host virtualbox network for you by creating a new host-only network, using this script: https://github.com/dcos/dcos-vagrant/blob/master/provision/bin/vbox-network.sh

Does that not work for your setup or did you have some other non-default configuration that it doesn't account for?

**Comment by anthonyskipper** [comment] 2016-05-17 23:48
It is a non-standard setup, with it spread across two physical machines.  I've had to fix the routing issue before, it's not a dcos issue.   This part that was new was this was the first time the inability to resolve dns persisted after fixing the routing.  The only difference this cluster build was I used the new 0.6.0 vagrant box.

**Comment by karlkfi** [comment] 2016-05-18 00:13
ah. ok. if you're using custom networking then i don't expect dcos-vagrant to help you much.

But yes, these are symptoms of netwokring problems. They could be vbox related or they could be DNS related or hostname related. It's hard to know without a fair amount of other information.

**Comment by piwi3910** [comment] 2016-05-18 07:54
Haha funny, you do remember we don’t have dns.
So no yum at the moment

**Comment by karlkfi** [comment] 2016-05-18 19:23
To temporarily fix dns, you can add `nameserver 8.8.8.8` to `/etc/resolv.conf`. Then you can install the tools you want, revert the change and figure out what the behavior was.

It's looking like the recent disabling of NetworkManager *may* have broken DNS resolution on the base os image, which isn't "resolved" until DC/OS is installed and modifies `/etc/resolv.conf`.

I'm still investigating.

**Comment by karlkfi** [comment] 2016-05-18 19:52
Progress: Disabling NetworkManager in the latest dcos-vagrant-box broke DNS resolution on the base os image. So the only DNS being set up is the `/etc/resolv.conf` modification by the DC/OS installer based on the `resolvers` value in `<repo>/etc/config-<version>.yaml`.

We initially disabled NetworkManager to improve Windows support, but it's unclear if it was actually required, after having needed to make other additional changes to dcos-vagrant-box.

So we'll have to verify if re-enabling works on Windows. If it does, that's the fix. If it doesn't, we'll need to figure another non-standard way to manage DNS configuration using Vagrant/VirtualBox.

**Comment by karlkfi** [comment] 2016-05-18 20:37
Here's an option to try... 

Set `resolvers` in `<repo>/etc/config-<version>.yaml`:

```
resolvers:
- 10.0.2.3
```

That should make DC/OS delegate to the VirtualBox NAT DNS Host Resolver, which should continue to work even if the host DNS resolution configuration changes.

**Comment by karlkfi** [comment] 2016-05-18 22:15
I've pushed this default change to master. Please test it and let me know.

**Comment by estebanlll** [comment] 2016-05-19 10:24
Works on the masters and slaves and agents, but for the boot still the same issues when I am trying to use the private docker registry.

the message I got is:
> Error while pulling image: Get https://index.docker.io/v1/repositories/vertx/vertx3/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:35420->[::1]:53: read: connection refused

**Comment by karlkfi** [comment] 2016-05-19 18:00
Yes, that's because DC/OS doesn't get installed on the boot machine and the OS image DNS config isn't working due to NetworkManager being disabled. 

I'm testing a fix now that will repair DNS on the os image: https://github.com/dcos/dcos-vagrant-box/commit/316ee4b44b5d591c66891514a3eeed62033a7eb9

**Comment by karlkfi** [comment] 2016-05-19 21:51
That box is released now as 0.6.1
Try it out!

**Comment by bendalby82** [comment] 2016-05-20 12:03
@karlkfi I updated Vagrant box, pulled latest dcos-vagrant repo, and re-downloaded dcos_generate_config.sh. Re-ran `vagrant up m1 a1 p1 boot` and can confirm that login with GitHub account works, and can now see Packages populated on the Universe menu item.

My environment:
Vagrant 1.8.1
Virtual box 5.0.20
OSX 10.10.5

Thanks!

**Closed** 2016-05-20 16:12 UTC

**Comment by drajguru** [comment] 2016-05-22 22:53
In case anyone else hits this issue, VirtualBox may need to be updated.

I was still getting the issue with the new Vagrant box, but it resolved after updating VirtualBox to 5.0.20

**Comment by michaelharrer** [comment] 2016-06-02 15:11
I still have the same issue, even after setting up my environment with tested versions:

Vagrant 1.8.1
VBox 5.0.20
OSX 10.11.4

I dont get any error msg, the github login just redirects to the loginpage again.

**Comment by karlkfi** [comment] 2016-06-02 17:50
@michaelharrer Please make a new JIRA ticket. Your symptom doesn't sound the same as the others listed here. https://dcosjira.atlassian.net/projects/VAGRANT

**Comment by VMTrooper** [comment] 2016-06-03 05:58
@karlkfi I confirmed that if I try the GitHub login, I see the same behavior that @michaelharrer observed. If I destroy the environment and rebuild it and use the Google login, I can get into the UI.

@michaelharrer did you open that JIRA ticket? if so, can you post the URL so that I can add comments to it.

**Comment by michaelharrer** [comment] 2016-06-03 18:20
@VMTrooper + @karlkfi https://dcosjira.atlassian.net/browse/VAGRANT-19
Thx in advance!
