### ISSUE TITLE
install dies on malformed metadata.json

### ISSUE THREAD

**Issue by alantech21** [dcos/dcos-vagrant#64] opened 2016-05-19 20:49 UTC
While trying to do a setup of dcos-vagrant using vagrant 1.8.1, dcos-vagant 0.6.0, and dcos 1.7, it fails. The command I was executing at the time was:

vagrant up m1 a1 p1 boot

and it returned the following error:

==> m1: Box 'mesosphere/dcos-centos-virtualbox' could not be found. Attempting to find and install...
    m1: Box Provider: virtualbox
    m1: Box Version: ~> 0.6.0
==> m1: Loading metadata for box 'https://downloads.dcos.io/dcos-vagrant/metadata.json'
    m1: URL: https://downloads.dcos.io/dcos-vagrant/metadata.json
The metadata for the box was malformed. The exact error
is shown below. Please contact the maintainer of the box so
that this issue can be fixed.

814: unexpected token at ''

**Comment by karlkfi** [comment] 2016-05-19 21:00
Looks like the cache or S3 file is borked... looking into it

**Comment by karlkfi** [comment] 2016-05-19 21:01
Duplicate of https://dcosjira.atlassian.net/browse/DCOS-126

**Closed by karlkfi** 2016-05-19 21:01 UTC
